// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.DbContexts;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext_00013540))]
    [Migration("20240317161727_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.UserTask_00013540", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Finish writing the project proposal document.",
                            DueDate = new DateTimeOffset(new DateTime(2024, 3, 24, 21, 17, 26, 596, DateTimeKind.Unspecified).AddTicks(3458), new TimeSpan(0, 5, 0, 0, 0)),
                            Priority = 0,
                            Status = 1,
                            Title = "Complete project proposal"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discuss project requirements with the client.",
                            DueDate = new DateTimeOffset(new DateTime(2024, 3, 20, 21, 17, 26, 596, DateTimeKind.Unspecified).AddTicks(3503), new TimeSpan(0, 5, 0, 0, 0)),
                            Priority = 1,
                            Status = 2,
                            Title = "Meeting with client"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Create a presentation for the project update meeting.",
                            DueDate = new DateTimeOffset(new DateTime(2024, 3, 27, 21, 17, 26, 596, DateTimeKind.Unspecified).AddTicks(3506), new TimeSpan(0, 5, 0, 0, 0)),
                            Priority = 2,
                            Status = 3,
                            Title = "Prepare presentation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
